apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: <deployment_name>
    app.kubernetes.io/name: <deployment_name>
  name: <deployment_name>
  namespace: <namespace>
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: <deployment_name>
    app.kubernetes.io/name: <deployment_name>
  sessionAffinity: None
  type: ClusterIP
